name: szabsync
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  badges: ^3.1.2
  flutter_credit_card: ^4.0.1
  fluttertoast: ^8.2.2
  qr_flutter: ^4.1.0
  firebase_core: ^2.19.0
  cloud_firestore: ^4.11.0
  shared_preferences: ^2.2.2
  syncfusion_flutter_charts: ^23.1.42
  firebase_storage: ^11.4.1
  google_maps_flutter: ^2.5.0
  http: ^1.2.0
  firebase_messaging: ^14.7.3
  emoji_picker_flutter: ^1.6.3
  f_datetimerangepicker: ^0.2.0
  intl: ^0.18.1
  image_picker: ^1.0.4
  mime: ^1.0.4
  video_player: ^2.8.1
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  jiffy: ^6.2.1
  qrscan: ^0.3.3
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: DMSans
      fonts:
        - asset: fonts/DMSans.ttf
    - family: Poppins
      fonts:
        - asset: fonts/Poppins.ttf
  